name: .NET CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests (without performance)
        run: dotnet test --configuration Release --no-build --filter "Category!=Performance"

      - name: Publish API
        run: dotnet publish Api/TourGuide.csproj -c Release -o publish

      - name: Create ZIP artifact
        run: |
          cd publish
          zip -r ../tourguide-api.zip .

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-api-zip
          path: tourguide-api.zip